version: "3.7"
services:
    db:
        image: mdillon/postgis:10-alpine
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - "5432:5432"
        env_file:
            - secrets/sausage-db.dev.env
        volumes:
            # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
            - ./db-pg/postgresql.conf:/etc/postgresql/postgresql.conf

            # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
            # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/

            # Enable this to store the PostgreSQL data on the host
            - ./db-pg/data:/var/lib/postgresql/data
    memcached:
        image: memcached
        expose:
            - "11211"
    django:
        image: demsausage/django:latest
        command: supervisord
        volumes:
            - ./logs/django:/app/logs:delegated
        # ports:
        #     - "8000:8000"
        env_file:
            - secrets/sausage-web.prod-local.env
            - secrets/sausage-web-db.dev.env
        depends_on:
            - db
    nginx_prod:
        image: demsausage/nginx-prod:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
        depends_on:
            - django
        ports:
            - "443:443"
            - "444:444"
            - "8001:8001"
        environment:
            - HTTPS_ENABLED=TRUE
            - SERVER_NAME=localhost
            - DJANGO_LOCATION=django:8000
