# https://github.com/marketplace/actions/github-issues-to-azure-devops
# name: Sync issues to Azure DevOps

# on:
#   issues:
#     types:
#       [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

# jobs:
#   alert:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: danhellem/github-actions-issue-to-work-item@master
#         env:
#           ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
#           github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
#           ado_organization: "contentsmaydiffer"
#           ado_project: "Democracy Sausage"
#           ado_area_path: ""
#           ado_iteration_path: ""
#           ado_wit: "Issue"
#           ado_new_state: "New"
#           ado_active_state: "Active"
#           ado_close_state: "Closed"
#           ado_bypassrules: true
#           log_level: 100
